apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ghost-ingress
#  namespace: sandbox
  annotations:
#    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
#    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
#  tls:
#    - hosts:
#        - chevrutah.com
  rules:
    - host: shpiel.chevrutah.com
      http:
        paths:
          - path: /
            backend:
              serviceName: ghost-first
              servicePort: 80