apiVersion: apps/v1
kind: Deployment
metadata:
  name: corona-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: corona-app  
  template:
    metadata:
      labels:
        app: corona-app
    spec:
      containers:
      - name: corona
        image: ilanpillemer/corona
        imagePullPolicy: Always
        ports:
        - containerPort: 8080