apiVersion: apps/v1
kind: Deployment
metadata:
  name: corona-app
  namespace: corona
  annotations:
    flux.weave.works/automated: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: corona-app
  template:
    metadata:
      labels:
        app: corona-app
    spec:
      containers:
      - name: corona
        image: ilanpillemer/corona:88912220
        ports:
        - containerPort: 8080