apiVersion: apps/v1
kind: Deployment
metadata:
  name: corona-app
  namespace: corona
  annotations:
    fluxcd.io/automated: "true"  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: corona-app  
  template:
    metadata:
      labels:
        app: corona-app
    spec:
      containers:
      - name: corona
        image: ilanpillemer/corona:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080